// <auto-generated />
using System;
using LibrarySystemApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibrarySystemApi.Migrations
{
    [DbContext(typeof(BookLibraryDbContext))]
    [Migration("20250828093740_DateDataType")]
    partial class DateDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibrarySystemApi.BookLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pages")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            GenreId = 2,
                            ImageUrl = "obstacle-the-way.jpg",
                            Isbn = "9781591846352",
                            Pages = 224,
                            PublicationYear = 2014,
                            Title = "The Obstacle Is the Way"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 2,
                            GenreId = 2,
                            ImageUrl = "meditations.jpg",
                            Isbn = "9780140449334",
                            Pages = 304,
                            PublicationYear = 180,
                            Title = "Meditations"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 3,
                            GenreId = 2,
                            ImageUrl = "letters-from-stoic.jpg",
                            Isbn = "9780140442106",
                            Pages = 256,
                            PublicationYear = 65,
                            Title = "Letters from a Stoic"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 4,
                            GenreId = 2,
                            ImageUrl = "art-of-living.jpg",
                            Isbn = "9780061286056",
                            Pages = 144,
                            PublicationYear = 55,
                            Title = "The Art of Living"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 5,
                            GenreId = 4,
                            ImageUrl = "tools-of-titans.jpg",
                            Isbn = "9781328683786",
                            Pages = 704,
                            PublicationYear = 2016,
                            Title = "Tools of Titans"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 6,
                            GenreId = 3,
                            ImageUrl = "laws-of-power.jpg",
                            Isbn = "9780140280197",
                            Pages = 452,
                            PublicationYear = 1998,
                            Title = "The 48 Laws of Power"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 7,
                            GenreId = 3,
                            ImageUrl = "atomic-habits.jpg",
                            Isbn = "9780735211292",
                            Pages = 320,
                            PublicationYear = 2018,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 8,
                            GenreId = 3,
                            ImageUrl = "win-friends-and-people.jpg",
                            Isbn = "9780671027032",
                            Pages = 291,
                            PublicationYear = 1936,
                            Title = "How to Win Friends and Influence People"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 9,
                            GenreId = 3,
                            ImageUrl = "effective-people.jpg",
                            Isbn = "9780743269513",
                            Pages = 381,
                            PublicationYear = 1989,
                            Title = "The 7 Habits of Highly Effective People"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 10,
                            GenreId = 4,
                            ImageUrl = "deep-work.jpg",
                            Isbn = "9781455586691",
                            Pages = 304,
                            PublicationYear = 2016,
                            Title = "Deep Work"
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            GenreId = 3,
                            ImageUrl = "ego-is-enemyjpg",
                            Isbn = "9781591847816",
                            Pages = 256,
                            PublicationYear = 2016,
                            Title = "Ego Is the Enemy"
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            GenreId = 3,
                            ImageUrl = "stillness-is-key.jpg",
                            Isbn = "9780525538585",
                            Pages = 288,
                            PublicationYear = 2019,
                            Title = "Stillness Is the Key"
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            GenreId = 2,
                            ImageUrl = "daily-stoic.jpg",
                            Isbn = "9780735211735",
                            Pages = 416,
                            PublicationYear = 2016,
                            Title = "Daily Stoic"
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 6,
                            GenreId = 3,
                            ImageUrl = "laws-of-human-nature.jpg",
                            Isbn = "9780525428145",
                            Pages = 624,
                            PublicationYear = 2018,
                            Title = "The Laws of Human Nature"
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 5,
                            GenreId = 4,
                            ImageUrl = "tribe-of-mentors.jpg",
                            Isbn = "9781328994967",
                            Pages = 624,
                            PublicationYear = 2017,
                            Title = "Tribe of Mentors"
                        });
                });

            modelBuilder.Entity("LibrarySystemApi.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "USA",
                            Name = "Ryan Holiday"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Rome",
                            Name = "Marcus Aurelius"
                        },
                        new
                        {
                            Id = 3,
                            Country = "Rome",
                            Name = "Seneca"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Turkey",
                            Name = "Epictetus"
                        },
                        new
                        {
                            Id = 5,
                            Country = "USA",
                            Name = "Tim Ferriss"
                        },
                        new
                        {
                            Id = 6,
                            Country = "USA",
                            Name = "Robert Greene"
                        },
                        new
                        {
                            Id = 7,
                            Country = "USA",
                            Name = "James Clear"
                        },
                        new
                        {
                            Id = 8,
                            Country = "USA",
                            Name = "Dale Carnegie"
                        },
                        new
                        {
                            Id = 9,
                            Country = "USA",
                            Name = "Stephen Covey"
                        },
                        new
                        {
                            Id = 10,
                            Country = "USA",
                            Name = "Cal Newport"
                        });
                });

            modelBuilder.Entity("LibrarySystemApi.Models.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CopyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookId", "Barcode")
                        .IsUnique();

                    b.HasIndex("BookId", "CopyNumber")
                        .IsUnique();

                    b.ToTable("BooksCopies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "123456789001",
                            BookId = 1,
                            CopyNumber = "copy #1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "123456734401",
                            BookId = 1,
                            CopyNumber = "copy #2",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "12355559001",
                            BookId = 1,
                            CopyNumber = "copy #3",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "123456789222",
                            BookId = 3,
                            CopyNumber = "copy #1",
                            Status = "Available"
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "1234567891111",
                            BookId = 1,
                            CopyNumber = "copy #4",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("LibrarySystemApi.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Philosophy"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Stoicism"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Self-help"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Productivity"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Biography"
                        },
                        new
                        {
                            Id = 6,
                            Name = "History"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Science"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Psychology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Business"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Non-fiction"
                        });
                });

            modelBuilder.Entity("LibrarySystemApi.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTimeOffset>("LoanDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MemberId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReturnDate")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("BookCopyId");

                    b.HasIndex("MemberId");

                    b.ToTable("Loans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookCopyId = 1,
                            DueDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTimeOffset(new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            MemberId = 1
                        },
                        new
                        {
                            Id = 2,
                            BookCopyId = 2,
                            DueDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTimeOffset(new DateTime(2024, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            MemberId = 2
                        },
                        new
                        {
                            Id = 3,
                            BookCopyId = 3,
                            DueDate = new DateTime(2024, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LoanDate = new DateTimeOffset(new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 1, 0, 0, 0)),
                            MemberId = 3
                        });
                });

            modelBuilder.Entity("LibrarySystemApi.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Mvog-Betsi, Baobab",
                            Email = "kebehclovis@gmail.com",
                            FullName = "Kebeh Clovis",
                            JoinedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+237 679695180"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Ohio, Bellevue",
                            Email = "amira.johnson@example.com",
                            FullName = "Amira Johnson",
                            JoinedDate = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+1 434534534455"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Obili",
                            Email = "david.lee@example.com",
                            FullName = "David Lee",
                            JoinedDate = new DateTime(2024, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+237 654432443"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nkolbisson",
                            Email = "fatima.ali@example.com",
                            FullName = "Fatima Ali",
                            JoinedDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+237 654345676"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Leke steet 1",
                            Email = "luca.rossi@example.com",
                            FullName = "Luca Rossi",
                            JoinedDate = new DateTime(2022, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+234 5334645345"
                        },
                        new
                        {
                            Id = 6,
                            Address = "",
                            Email = "sophia.mueller@example.com",
                            FullName = "Sophia Müller",
                            JoinedDate = new DateTime(2023, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "+237 674534321"
                        });
                });

            modelBuilder.Entity("LibrarySystemApi.BookLibrary", b =>
                {
                    b.HasOne("LibrarySystemApi.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystemApi.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("LibrarySystemApi.Models.BookCopy", b =>
                {
                    b.HasOne("LibrarySystemApi.BookLibrary", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibrarySystemApi.Models.Loan", b =>
                {
                    b.HasOne("LibrarySystemApi.Models.BookCopy", "BookCopy")
                        .WithMany()
                        .HasForeignKey("BookCopyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibrarySystemApi.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookCopy");

                    b.Navigation("Member");
                });
#pragma warning restore 612, 618
        }
    }
}
